### ISSUE TITLE
Ответ об ошибке от демона при запуске docker compose

### ISSUE THREAD

**Issue by SergGrebnev** [SergGrebnev/automation_basics_3_1_1_Docker#1]
# Описание
Docker compose должен создать контейнер.

# Шаги воспроизведения
1. Запустить и авторизоваться в приложении Docker Desktop
2. Открыть проект в IDEA
3. Запустить в терминале Docker compose командой docker compose up

*Ожидаемый результат:* Контейнер создан.
*Фактический результат:* Ответ об ошибке от демона.

# Скриншот
![image](https://github.com/user-attachments/assets/a61029c1-fcb6-496f-ba56-82c2678d7c07)

# Окружение
* **Операционная система** Windows 11
* **IDE** IntelliJ IDEA 2024.2.0.1 (Community Edition)
* **Java** corretto-18.0.2

[Ссылка на исходники проекта на GitHub](https://github.com/SergGrebnev/automation_basics_3_1_1_Docker)

**Comment by andrew-pahomov** [comment]
Добрый день           

Похожая проблема с решением описана в форуме https://forums.docker.com/t/unauthorized-incorrect-username-or-password/35677/26, думаю стоит попробовать его

**Comment by SergGrebnev** [comment]
> Добрый день
> 
> Похожая проблема с решением описана в форуме https://forums.docker.com/t/unauthorized-incorrect-username-or-password/35677/26, думаю стоит попробовать его

Заработало когда авторизовался в докере через профиль гитхаб
